export const kinds=['Crash','Medical emergency','Mechanical failure','Unsafe road','Personal safety','Other','Bike breakdown','Accident','Out of fuel','Lost / separated','Other emergency'];
export function text(value,max=120){if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error('Please check the required fields.');return value.trim();}
export function number(value,min,max){if(!Number.isFinite(value)||value<min||value>max)throw new Error('Value outside the allowed range.');return value;}
export function coordinates(value,now=Date.now()){if(!value)return null;return {lat:number(value.lat,-90,90),lng:number(value.lng,-180,180),at:now};}
export function distance(a,b){const rad=x=>x*Math.PI/180;const dlat=rad(b.lat-a.lat),dlng=rad(b.lng-a.lng);return 6371000*2*Math.asin(Math.sqrt(Math.min(1,Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2)));}
export function changeRide(original,uid,action,data={},now=Date.now()){
 const r=structuredClone(original),member=r.members.find(m=>m.id===uid);if(!member)throw new Error('Join this ride first.');
 const host=()=>{if(r.hostId!==uid)throw new Error('Only the host can do this.');};
 const ongoing=()=>{if(r.status==='completed')throw new Error('This ride is complete.');};
 const system=t=>r.messages.push({id:`system-${now}`,sender:'Ride update',text:t,type:'system',at:now});
 const log=(type,message,severity='INFO')=>{r.timeline??=[];r.timeline.push({id:`${type}-${now}-${uid}`,type,text:message,severity,at:now,userId:uid,simulated:!!r.simulated});r.timeline=r.timeline.slice(-200);};
 switch(action){
 case 'start':host();if(!['upcoming','paused'].includes(r.status))throw new Error('Ride cannot be started.');if(r.members.some(m=>!m.ready)&&!data.confirmUnready)throw new Error('Some riders are not ready.');r.status='active';r.startedAt??=now;log('RIDE_STARTED','Ride started.');system('The ride has started. Stay with the group and ride safely.');break;
 case 'pause':host();if(r.status!=='active')throw new Error('Ride is not active.');r.status='paused';log('GROUP_STOPPED','Leader paused the ride.');r.members.forEach(m=>m.location=null);system('Ride paused. Stop in a safe location.');break;
 case 'end':host();if(!['active','paused'].includes(r.status))throw new Error('Ride is not in progress.');r.status='completed';r.endedAt=now;r.simulationRunning=false;if(r.simulated)r.progress=1;r.members.forEach(m=>m.location=null);r.events.forEach(e=>e.location=null);if(!r.simulated)r.replay=[];log('RIDE_ENDED','Ride completed. Live positions removed.');system('Ride completed. Thank you for riding together.');break;
 case 'ready':ongoing();member.ready=!!data.ready;if(!r.events.some(e=>e.userId===uid&&!['Resolved','Cancelled'].includes(e.status))&&r.status==='upcoming')member.status=member.ready?'Ready':'Not ready';member.lastUpdated=now;break;
 case 'status':ongoing();if(r.events.some(e=>e.userId===uid&&!['Resolved','Cancelled'].includes(e.status)))throw new Error('The host must resolve your open emergency first.');if(!['Riding','Stopped','Delayed','Offline'].includes(data.status))throw new Error('Invalid rider status.');member.status=data.status;member.statusSince=now;member.lastUpdated=now;break;
 case 'location':if(r.status!=='active'&&data.location)throw new Error('Location sharing requires an active ride.');member.location=coordinates(data.location,now);member.lastUpdated=now;if(member.location){const peers=r.members.filter(m=>m.location&&now-m.location.at<120000&&m.status!=='Offline');const center=peers.length>1?{lat:peers.reduce((a,m)=>a+m.location.lat,0)/peers.length,lng:peers.reduce((a,m)=>a+m.location.lng,0)/peers.length}:null;const gap=center?distance(member.location,center):0;const emergency=r.events.some(e=>e.userId===uid&&!['Resolved','Cancelled'].includes(e.status));if(center&&gap>r.warningDistance){member.separatedSince??=now;if(now-member.separatedSince>=r.delayMinutes*60000&&!emergency&&member.status!=='Separated'){member.status='Separated';log('RIDER_SEPARATED',`${member.name} is separated. Regroup at a safe location.`,'WARNING');}}else{delete member.separatedSince;if(!emergency&&['Separated','Offline'].includes(member.status))member.status='Riding';}}else delete member.separatedSince;break;
 case 'message':ongoing();if(data.type==='announcement')host();r.messages.push({id:`message-${now}-${uid}`,sender:member.name,text:text(data.text,2000),type:data.type==='announcement'?'announcement':'text',at:now});break;
 case 'sos':if(r.status!=='active'&&r.status!=='paused')throw new Error('SOS requires an active ride.');if(!kinds.includes(data.type))throw new Error('Select an emergency type.');if(r.events.some(e=>e.userId===uid&&!['Resolved','Cancelled'].includes(e.status)))throw new Error('Your SOS is already open.');r.events.push({id:`sos-${now}-${uid}`,userId:uid,name:member.name,type:data.type,status:'Reported',at:now,location:coordinates(data.location,now)});member.status='Emergency';log('SOS_TRIGGERED',`${member.name} requested assistance.`,'CRITICAL');system(`Emergency reported by ${member.name}.`);break;
 case 'cancelSos':{const e=r.events.find(e=>e.id===data.eventId);if(!e||e.userId!==uid)throw new Error('Only the reporting rider can cancel this SOS.');if(['Resolved','Cancelled'].includes(e.status))throw new Error('This SOS is already closed.');e.status='Cancelled';e.location=null;e.resolvedAt=now;member.status='Safe';log('SOS_RESOLVED',`${member.name} cancelled their SOS.`);break;}
 case 'safe':ongoing();if(r.events.some(e=>e.userId===uid&&!['Resolved','Cancelled'].includes(e.status)))throw new Error('Cancel or resolve your SOS first.');member.status='Safe';member.safeAt=now;member.lastUpdated=now;log('RIDER_SAFE',`${member.name} marked themselves safe.`);break;
 case 'role':host();ongoing();{const target=r.members.find(m=>m.id===data.userId);if(!target||target.id===r.hostId)throw new Error('Choose a rider other than the leader.');r.sweepId=target.id;r.members.forEach(m=>m.role=m.id===r.hostId?'leader':m.id===target.id?'sweep':'rider');log('ROLE_UPDATED',`${target.name} is the sweep rider.`);break;}
 case 'checkIn':ongoing();{const required=['Helmet','Vehicle ready','Phone charged','Emergency contact available','Fuel sufficient','License / required documents'];if(!Array.isArray(data.items)||data.items.length!==6||!required.every(i=>data.items.includes(i)))throw new Error('Complete each self-check item.');member.checkIn=required;member.ready=true;if(r.status==='upcoming')member.status='Ready';log('RIDER_CHECKED_IN',`${member.name} completed the self-check.`);break;}
 case 'hazard':ongoing();{const types=['Pothole','Accident','Road construction','Slippery road','Debris','Animal','Traffic','Poor visibility','Flooding','Sharp turn','Road closure','Police / traffic control'];if(!types.includes(data.type)||!['Low','Moderate','High'].includes(data.severity))throw new Error('Select a hazard type and severity.');const location=coordinates(data.location,now);if(!location)throw new Error('A hazard requires a known location.');r.hazards??=[];if(r.hazards.length>=100)throw new Error('Hazard report limit reached.');const photo=data.photo||'';if(typeof photo!=='string'||photo.length>120000||photo&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(photo))throw new Error('Invalid hazard image.');if(photo&&r.hazards.reduce((n,h)=>n+(h.photo?.length||0),0)+photo.length>200000)throw new Error('Ride photo capacity reached. Submit this hazard without a photo.');r.hazards.push({id:`hazard-${now}-${uid}`,type:data.type,severity:data.severity,description:text(data.description,500),direction:text(data.direction,120),location,reportedBy:uid,at:now,confirmations:[uid],disputes:[],photo,simulated:!!r.simulated});log('HAZARD_REPORTED',`${data.type} reported · unverified.`,'WARNING');break;}
 case 'voteHazard':ongoing();{const h=r.hazards?.find(h=>h.id===data.hazardId);if(!h)throw new Error('Hazard not found.');h.confirmations=h.confirmations.filter(x=>x!==uid);h.disputes=h.disputes.filter(x=>x!==uid);(data.present?h.confirmations:h.disputes).push(uid);log('HAZARD_CONFIRMED',`${member.name} ${data.present?'confirmed':'disputed'} a ${h.type.toLowerCase()} report.`);break;}
 case 'route':host();ongoing();r.destination=text(data.destination,180);if(!Array.isArray(data.stops)||data.stops.length>15)throw new Error('Maximum 15 stops.');r.stops=data.stops.map(s=>text(s,120));log('ROUTE_UPDATED','Leader updated the route. Review before continuing.','WARNING');break;
 case 'respond':host();{const e=r.events.find(e=>e.id===data.eventId);if(!e)throw new Error('Emergency not found.');const transitions={'Reported':['Acknowledged','Help on the way','Resolved'],'Acknowledged':['Help on the way','Resolved'],'Help on the way':['Resolved']};if(!transitions[e.status]?.includes(data.status))throw new Error('Invalid emergency transition.');e.status=data.status;if(data.status==='Resolved'){e.resolvedAt=now;e.location=null;log('SOS_RESOLVED',`${e.name}: assistance event resolved.`);const m=r.members.find(m=>m.id===e.userId);if(m)m.status='Stopped';}system(`${e.name}: ${data.status}.`);}break;
 case 'settings':host();ongoing();r.warningDistance=number(data.warningDistance,100,10000);r.criticalDistance=number(data.criticalDistance,r.warningDistance,20000);r.delayMinutes=number(data.delayMinutes,1,30);break;
 case 'stop':host();ongoing();if(r.stops.length>=15)throw new Error('Maximum 15 stops.');r.stops.push(text(data.stop));break;
 case 'leave':if(r.hostId===uid)throw new Error('Hosts must delete the ride instead.');r.members=r.members.filter(m=>m.id!==uid);r.memberIds=r.memberIds.filter(id=>id!==uid);r.events=r.events.filter(e=>e.userId!==uid);break;
 case 'remove':host();if(data.userId===uid)throw new Error('You cannot remove the host.');r.members=r.members.filter(m=>m.id!==data.userId);r.memberIds=r.memberIds.filter(id=>id!==data.userId);r.events=r.events.filter(e=>e.userId!==data.userId);break;
 default:throw new Error('Unknown action.');
 }r.messages=r.messages.slice(-150);return r;
}
