import test from 'node:test';
import assert from 'node:assert/strict';
import {decodeRide,encodeRide,validateFix,locationState} from './realtime-model.mjs';
const now=Date.now();const point={userId:'a',rideId:'ride',latitude:48,longitude:9,accuracy:8,heading:90,speed:10,altitude:700,timestamp:now,status:'Riding'};
test('GPS rejects future, stale, invalid and physically implausible fixes',()=>{assert.equal(validateFix(point,null,now),point);for(const bad of [{latitude:91},{longitude:181},{timestamp:now+5000},{timestamp:now-20000},{accuracy:200},{heading:400},{speed:200}])assert.throws(()=>validateFix({...point,...bad},null,now));assert.throws(()=>validateFix({...point,latitude:49}, {...point,timestamp:now-3000},now),/GPS_ANOMALY/);assert.throws(()=>validateFix(point,point,now),/advance/);});
test('GPS retains supported telemetry and accepts realistic movement',()=>{const next={...point,latitude:48.0001,timestamp:now+3000};assert.equal(validateFix(next,point,now+3000),next);assert.equal(next.heading,90);assert.equal(next.speed,10);});
test('locations become stale and offline instead of being shown as current',()=>{const member={location:{at:now,accuracy:8}};assert.equal(locationState(member,now+10000),'LIVE');assert.equal(locationState(member,now+21000),'STALE');assert.equal(locationState(member,now+61000),'OFFLINE');assert.equal(locationState({location:null},now),'UNAVAILABLE');assert.equal(locationState({location:{at:now,accuracy:74}},now),'WEAK GPS');});
test('Realtime schema uses user-keyed GPS and strips telemetry from public membership records',()=>{const raw={leaderId:'a',status:'active',members:{a:{id:'a',name:'Rider',status:'Riding',role:'leader'}},locations:{a:point},presence:{a:{connected:true,battery:74}},messages:{},incidents:{},stops:[]};const ride=decodeRide('ride',raw);assert.equal(ride.members[0].location.heading,90);assert.equal(ride.members[0].speed,36);assert.equal(ride.members[0].battery,74);const encoded=encodeRide(ride,raw);assert.equal(encoded.members.a.location,undefined);assert.equal(encoded.members.a.battery,undefined);assert.equal(encoded.locations.a.userId,'a');});
test('ending a real ride clears all live locations and presence',()=>{const raw={leaderId:'a',members:{a:{id:'a',name:'Rider'}},locations:{a:point},presence:{a:{connected:true}}};const ride=decodeRide('ride',raw);ride.status='completed';const encoded=encodeRide(ride,raw);assert.deepEqual(encoded.locations,{});assert.deepEqual(encoded.presence,{});});
