import {getDatabase} from 'firebase-admin/database';
import {onCall,HttpsError} from 'firebase-functions/v2/https';
import {onValueWritten,onValueCreated} from 'firebase-functions/v2/database';
import {onTaskDispatched} from 'firebase-functions/v2/tasks';
import {getFunctions} from 'firebase-admin/functions';
import {getMessaging} from 'firebase-admin/messaging';
import {onSchedule} from 'firebase-functions/v2/scheduler';
import {randomInt,randomUUID} from 'node:crypto';
import {changeRide,text,number,distance} from './domain.mjs';
import {decodeRide,encodeRide,validateFix} from './realtime-model.mjs';
const options={region:'europe-west1',enforceAppCheck:true,maxInstances:20,timeoutSeconds:60};
const database=()=>getDatabase();
const codeValue=value=>{const code=text(value,12).toUpperCase();if(!/^LR-[A-Z2-9]{5}$/.test(code))throw new Error('Enter an LR- join code.');return code;};
const idValue=value=>{const id=text(value,100);if(/[.#$\[\]/]/.test(id))throw new Error('Invalid record ID.');return id;};
async function limit(uid,bucket,max=30){const minute=Math.floor(Date.now()/60000);let allowed=false;await database().ref(`liveRateLimits/${uid}/${bucket}`).transaction(old=>{const count=old?.minute===minute?old.count:0;allowed=count<max;return allowed?{minute,count:count+1}:undefined;});if(!allowed)throw new HttpsError('resource-exhausted','Too many requests. Try again in a minute.');}
const endpoint=fn=>onCall(options,async req=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in to continue.');try{return await fn(req.auth.uid,req.data||{});}catch(error){if(error instanceof HttpsError)throw error;throw new HttpsError('failed-precondition',error.message||'Request failed.');}});
async function profile(uid){const snapshot=await database().ref(`profiles/${uid}`).get();const p=snapshot.val();if(!p?.name)throw new Error('Save your rider profile before creating or joining a ride.');return p;}
async function codeRide(code){const s=await database().ref(`liveJoinCodes/${codeValue(code)}`).get();if(!s.exists())throw new Error('No open ride matches this code.');return s.val().rideId;}
export const liveCreateRide=endpoint(async(uid,d)=>{
 await limit(uid,'create',5);const p=await profile(uid),id=randomUUID(),now=Date.now();
 if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(d.departure))throw new Error('Check the date and departure time.');
 const stops=(d.stops||[]).map(s=>text(s,120));if(stops.length>15)throw new Error('Maximum 15 waypoints.');
 const visibility=d.visibility||'Private';if(!['Private','Invite only','Group members','Public'].includes(visibility))throw new Error('Invalid privacy choice.');
 const ride={id,name:text(d.name,100),description:typeof d.description==='string'?d.description.slice(0,1000):'',start:text(d.start,180),destination:text(d.destination,180),stops,date:d.date,departure:d.departure,maxRiders:number(d.maxRiders,1,50),visibility,difficulty:d.difficulty||'Moderate',rideType:d.rideType||'Motorcycle',status:'upcoming',hostId:uid,hostName:text(p.name,120),memberIds:[uid],members:[{id:uid,name:p.name,photo:p.photo||'',vehicle:p.privacy?.profileVisibility==='Only me'?'':p.vehicle||'',role:'leader',ready:false,status:'Not ready',joinedAt:now,lastUpdated:now}],messages:[],events:[],hazards:[],timeline:[{id:randomUUID(),type:'RIDE_CREATED',text:'Ride created.',severity:'INFO',at:now,userId:uid}],warningDistance:500,criticalDistance:1000,delayMinutes:1,createdAt:now,recordReplay:d.recordReplay===true,retentionDays:7,escalationSeconds:{leader:10,sweep:20,group:30}};
 for(let retry=0;retry<8;retry++){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',code='LR-'+Array.from({length:5},()=>alphabet[randomInt(alphabet.length)]).join('');const result=await database().ref(`liveJoinCodes/${code}`).transaction(old=>old?undefined:{rideId:id,createdAt:now});if(!result.committed)continue;ride.code=code;try{await database().ref().update({[`rides/${id}`]:encodeRide(ride),[`userRides/${uid}/${id}`]:true});return{id,code};}catch(e){await database().ref(`liveJoinCodes/${code}`).remove();throw e;}}
 throw new Error('Unable to reserve a join code.');
});
export const liveLookupRide=endpoint(async(uid,d)=>{await limit(uid,'lookup',10);const id=await codeRide(d.code),s=await database().ref(`rides/${id}`).get(),r=s.val();if(!r||r.status==='completed')throw new Error('This ride has ended.');const members=Object.values(r.members||{});return{id,name:r.name,hostName:r.hostName,start:r.start,destination:r.destination,date:r.date,departure:r.departure,riderCount:members.length,maxRiders:r.maxRiders,stops:r.stops||[],sweepName:r.members?.[r.sweepId]?.name||'Not assigned',recordReplay:!!r.recordReplay,privacy:r.visibility};});
export const liveJoinRide=endpoint(async(uid,d)=>{await limit(uid,'join',10);if(d.briefingAccepted!==true)throw new Error('Accept the safety briefing first.');const p=await profile(uid),id=await codeRide(d.code),now=Date.now();let failure='Ride unavailable.';const result=await database().ref(`rides/${id}`).transaction(raw=>{if(!raw)return null;if(raw.status==='completed'){failure='This ride has ended.';return;}if(raw.members?.[uid])return raw;if(Object.keys(raw.members||{}).length>=raw.maxRiders){failure='This ride is full.';return;}if(raw.recordReplay&&d.replayAccepted!==true){failure='Consent to private replay recording is required for this ride.';return;}raw.members??={};raw.members[uid]={id:uid,name:text(p.name,120),photo:p.photo||'',vehicle:p.privacy?.profileVisibility==='Only me'?'':p.vehicle||'',role:'rider',status:'Not ready',ready:false,joinedAt:now,lastUpdated:now};raw.timeline??={};const eid=randomUUID();raw.timeline[eid]={id:eid,type:'RIDER_JOINED',text:`${p.name} joined.`,severity:'INFO',at:now,userId:uid};return raw;});if(!result.committed||!result.snapshot.exists())throw new Error(failure);await database().ref(`userRides/${uid}/${id}`).set(true);return{id};});
export const liveRideAction=endpoint(async(uid,d)=>{
 await limit(uid,'action',45);const id=idValue(d.rideId);let failure='Ride unavailable.';let removed=[];let code='';
 const result=await database().ref(`rides/${id}`).transaction(raw=>{if(!raw)return null;try{if(!raw.members?.[uid])throw new Error('Join this ride first.');const now=Date.now(),r=decodeRide(id,raw);code=r.code;
 if(d.action==='delete'){if(r.hostId!==uid)throw new Error('Only the leader can delete this ride.');removed=r.memberIds;return null;}
 if(d.action==='location')throw new Error('Publish only your own location through Realtime Database.');
 if(d.action==='sharedRoute'){if(r.hostId!==uid||r.status==='completed')throw new Error('Only the active ride leader can publish routes.');const route=d.route;if(!route||!Array.isArray(route.path)||route.path.length<2||route.path.length>10000)throw new Error('Invalid route geometry.');route.path.forEach(p=>{number(p.lat,-90,90);number(p.lng,-180,180);});if(route.waypoints&&!Array.isArray(route.waypoints))throw new Error('Invalid waypoints.');for(const p of (route.waypoints||[]).slice(0,16)){number(p.lat,-90,90);number(p.lng,-180,180);}number(route.distanceMeters,0,20000000);number(route.durationSeconds,0,1000000);r.sharedRoute={path:route.path,waypoints:(route.waypoints||[]).slice(0,16),distanceMeters:route.distanceMeters,durationSeconds:route.durationSeconds,provider:'google',updatedAt:now,revision:(raw.sharedRoute?.revision||0)+1};r.totalKm=route.distanceMeters/1000;r.estimatedMinutes=route.durationSeconds/60;r.timeline.push({id:randomUUID(),type:'ROUTE_UPDATED',text:'Leader published a new Google Maps route.',severity:'WARNING',at:now,userId:uid});return encodeRide(r,raw);}
 if(d.action==='regroup'){if(r.hostId!==uid||r.status!=='active')throw new Error('Only the active ride leader can set a regroup point.');const point=d.point;number(point?.lat,-90,90);number(point?.lng,-180,180);r.regroupPoint={lat:point.lat,lng:point.lng,label:text(d.label||'Leader-selected regroup point',180),at:now};r.timeline.push({id:randomUUID(),type:'REGROUP_REQUESTED',text:'Leader selected a regroup point. Confirm it is a safe place to stop.',severity:'WARNING',at:now,userId:uid});return encodeRide(r,raw);}
 const gps=raw.locations?.[uid];const sosLocation=gps&&now-gps.timestamp<120000?{lat:gps.latitude,lng:gps.longitude}:null;let next=changeRide(r,uid,d.action,d.action==='sos'?{...d,location:sosLocation}:d,now);if(d.action==='sos'){const incident=next.events.find(e=>e.userId===uid&&e.at===now);if(incident&&gps&&sosLocation){incident.location.at=gps.timestamp;incident.lastKnownSpeed=gps.speed!=null?Math.round(gps.speed*3.6):null;}}if(['route','stop'].includes(d.action))delete next.sharedRoute;if(d.action==='end'&&raw.recordReplay){next.replay=raw.replay||{};next.recordingExpiresAt=now+7*86400000;}
 removed=r.memberIds.filter(member=>!next.memberIds.includes(member));for(const member of removed)next.timeline.push({id:randomUUID(),type:'RIDER_LEFT',text:(r.members.find(m=>m.id===member)?.name||'Rider')+' left the ride.',severity:'INFO',at:now,userId:member});return encodeRide(next,raw);
 }catch(e){failure=e.message;return;}});
 if(!result.committed||(d.action!=='delete'&&!result.snapshot.exists()))throw new Error(failure);const updates={};if(d.action==='delete')updates[`rideReplays/${id}`]=null;for(const member of removed)updates[`userRides/${member}/${id}`]=null;if(['end','delete'].includes(d.action)&&code)updates[`liveJoinCodes/${code}`]=null;if(Object.keys(updates).length)await database().ref().update(updates);return{ok:true};
});
export const liveEmergencyContact=endpoint(async(uid,d)=>{await limit(uid,'contact',10);const s=await database().ref(`rides/${idValue(d.rideId)}`).get(),r=s.val();if(!r||r.leaderId!==uid)throw new Error('Only the ride leader may access consented contacts.');const incident=r.incidents?.[idValue(d.eventId)];if(!incident||['Resolved','Cancelled'].includes(incident.status))throw new Error('An open SOS is required.');const p=await profile(incident.userId);return p.sharePhone&&p.privacy?.contactVisibility!=='Only me'?{phone:p.phone||'',contactName:p.contactName||'',contactPhone:p.contactPhone||'',medicalInfo:p.medicalInfo||'',emergencyLanguage:p.emergencyLanguage||''}:{};});
export const liveDirectMessage=endpoint(async(uid,d)=>{await limit(uid,'direct-message',20);const rideId=idValue(d.rideId),to=idValue(d.to),s=await database().ref(`rides/${rideId}`).get(),r=s.val();if(!r?.members?.[uid]||!r.members[to]||r.status==='completed')throw new Error('Both riders must belong to an ongoing ride.');const sender=await profile(uid),recipient=await profile(to);const retention=Math.min(number(sender.privacy?.retentionDays||7,7,90),number(recipient.privacy?.retentionDays||7,7,90));const id=randomUUID(),message={id,rideId,from:uid,to,text:text(d.text,2000),at:Date.now(),expiresAt:Date.now()+retention*86400000};await database().ref().update({[`liveInboxes/${uid}/${rideId}/${id}`]:message,[`liveInboxes/${to}/${rideId}/${id}`]:message});return{ok:true};});
export const liveRegisterPushToken=endpoint(async(uid,d)=>{await limit(uid,'push-token',5);const token=text(d.token,4096);await database().ref(`livePushTokens/${uid}`).set({token,at:Date.now()});return{ok:true};});
export const liveMemberHistory=endpoint(async(uid,d)=>{await limit(uid,'history',5);const ride=(await database().ref(`rides/${idValue(d.rideId)}`).get()).val(),target=idValue(d.userId);if(!ride?.members?.[uid]||!ride.members[target])throw new Error('Join the same ride first.');const p=await profile(target);if(target!==uid&&p.privacy?.historyVisibility!=='Ride members')throw new Error('This rider keeps their history private.');const index=(await database().ref(`userRides/${target}`).get()).val()||{};const rides=await Promise.all(Object.keys(index).map(async id=>(await database().ref(`rides/${id}`).get()).val()));const completed=rides.filter(r=>r?.status==='completed');return{completedRides:completed.length,totalDurationMinutes:completed.reduce((n,r)=>n+Math.round(((r.endedAt||r.startedAt)-r.startedAt)/60000),0)};});
async function memberRide(uid,id){const r=(await database().ref(`rides/${idValue(id)}`).get()).val();if(!r?.members?.[uid])throw new Error('Join this ride first.');return r;}
async function weatherAt(place){try{const name=place.split(/[·,]/)[0].trim();const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(name)}&count=1&format=json`,{signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error();const match=(await response.json()).results?.[0];if(!match)throw new Error();const forecast=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${match.latitude}&longitude=${match.longitude}&current=temperature_2m,wind_speed_10m&hourly=visibility,precipitation_probability&forecast_days=1&timezone=auto`,{signal:AbortSignal.timeout(10000)});if(!forecast.ok)throw new Error();const w=await forecast.json(),hour=w.hourly.time.findIndex(t=>t.slice(0,13)===w.current.time.slice(0,13));return{place:`${place} (matched: ${match.name})`,temperature:w.current.temperature_2m,wind:w.current.wind_speed_10m,rain:w.hourly.precipitation_probability[hour]??null,visibility:w.hourly.visibility[hour]!=null?w.hourly.visibility[hour]/1000:null,at:w.current.time,warning:'Open-Meteo forecast · no official severe-weather alert feed connected',simulated:false};}catch{return{place,temperature:null,wind:null,rain:null,visibility:null,at:'Unavailable',warning:'Weather unavailable for this location.',simulated:false};}}
export const liveRouteWeather=endpoint(async(uid,d)=>{await limit(uid,'weather',5);const r=await memberRide(uid,d.rideId);return Promise.all([r.start,...(r.stops||[]).slice(0,6),r.destination].map(weatherAt));});
export const liveRideWeather=endpoint(async(uid,d)=>{await limit(uid,'weather',5);const r=await memberRide(uid,d.rideId),w=await weatherAt(r.destination);return{temperature:w.temperature,wind:w.wind,time:w.at,rainProbability:w.rain,location:w.place,source:'Open-Meteo'};});
export const livePresenceEvent=onValueWritten({ref:'/rides/{rideId}/presence/{uid}',region:'europe-west1',maxInstances:20},async event=>{const before=event.data.before.val(),after=event.data.after.val();if(!after||before?.connected===after.connected)return;const id=randomUUID();await database().ref(`rides/${event.params.rideId}`).transaction(r=>{if(!r)return null;const member=r?.members?.[event.params.uid];if(!member||r.status!=='active')return;r.timeline??={};r.timeline[id]={id,type:after.connected?'RIDER_RECONNECTED':'RIDER_OFFLINE',text:member.name+(after.connected?' connected to location sharing.':' disconnected. Last known GPS may be stale.'),severity:after.connected?'INFO':'WARNING',at:Date.now(),userId:event.params.uid};return r;});});
export const liveScheduleSos=onValueCreated({ref:'/rides/{rideId}/incidents/{incidentId}',region:'europe-west1',maxInstances:20,retry:true},async event=>{const r=(await database().ref(`rides/${event.params.rideId}`).get()).val();if(!r)return;const queue=getFunctions().taskQueue('locations/europe-west1/functions/liveEscalateSos');for(const target of ['leader','sweep','group']){const seconds=number(r.escalationSeconds?.[target]??{leader:10,sweep:20,group:30}[target],5,300);await queue.enqueue({rideId:event.params.rideId,incidentId:event.params.incidentId,target},{scheduleDelaySeconds:seconds});}});
export const liveEscalateSos=onTaskDispatched({region:'europe-west1',retryConfig:{maxAttempts:3,minBackoffSeconds:10},rateLimits:{maxConcurrentDispatches:5}},async request=>{const {rideId,incidentId,target}=request.data;if(!['leader','sweep','group'].includes(target))return;const reference=database().ref(`rides/${idValue(rideId)}`);let recipients=[];const result=await reference.transaction(r=>{if(!r)return null;const incident=r?.incidents?.[idValue(incidentId)];if(!incident||['Resolved','Cancelled'].includes(incident.status)||incident.escalations?.[target])return;recipients=target==='group'?Object.keys(r.members||{}):[target==='leader'?r.leaderId:r.sweepId].filter(Boolean);incident.escalations??={};incident.escalations[target]=Date.now();r.timeline??={};const id=`escalation-${incidentId}-${target}`;r.timeline[id]={id,type:'SOS_ESCALATED',text:`SOS reminder sent to ${target}. Notification delivery is not guaranteed.`,severity:'CRITICAL',at:Date.now(),userId:incident.userId,recipients};return r;});if(!result.committed)return;const tokens=(await Promise.all(recipients.map(async uid=>(await database().ref(`livePushTokens/${uid}`).get()).val()?.token))).filter(Boolean);if(tokens.length)await getMessaging().sendEachForMulticast({tokens,data:{rideId,incidentId,target},notification:{title:'LetsRide · assistance requested',body:'Open your ride to review an active SOS. No emergency services have been contacted.'}});});
export const liveLocationRecorded=onValueWritten({ref:'/rides/{rideId}/locations/{uid}',region:'europe-west1',maxInstances:20},async event=>{
 if(!event.data.after.exists())return;const point=event.data.after.val(),before=event.data.before.val();if(before&&point.timestamp<before.timestamp)return;try{validateFix(point,before,Date.parse(event.time)||Date.now());}catch{await event.data.after.ref.transaction(current=>current?.timestamp===point.timestamp?(before||null):undefined);return;}
 const rideRef=database().ref(`rides/${event.params.rideId}`),snapshot=await rideRef.get(),raw=snapshot.val();if(raw?.status!=='active'||!raw.members?.[event.params.uid])return;
 await rideRef.transaction(current=>{
  if(!current)return null;if(current.status!=='active'||current.locations?.[event.params.uid]?.timestamp!==point.timestamp)return;
  const member=current.members?.[event.params.uid];if(!member)return;
  const peers=Object.values(current.locations||{}).filter(p=>p.userId!==event.params.uid&&point.timestamp-p.timestamp>=0&&point.timestamp-p.timestamp<20000&&p.accuracy<=60);
  const center=peers.length?{lat:peers.reduce((n,p)=>n+p.latitude,0)/peers.length,lng:peers.reduce((n,p)=>n+p.longitude,0)/peers.length}:null;
  const gap=center&&point.accuracy<=60?distance({lat:point.latitude,lng:point.longitude},center):0;
  const sos=Object.values(current.incidents||{}).some(e=>e.userId===member.id&&!['Resolved','Cancelled'].includes(e.status));
  if(gap>current.warningDistance){member.separatedSince??=point.timestamp;if(point.timestamp-member.separatedSince>=current.delayMinutes*60000&&!sos&&member.status!=='Separated'){member.status='Separated';current.timeline??={};const id=randomUUID();current.timeline[id]={id,type:'RIDER_SEPARATED',text:member.name+' is separated. Stop safely and coordinate a regroup.',severity:'WARNING',at:point.timestamp,userId:member.id};}}
  else{delete member.separatedSince;if(member.status==='Separated'&&!sos)member.status='Riding';}
  const elapsed=before?(point.timestamp-before.timestamp)/1000:0;
  if(before&&elapsed>0&&elapsed<20)member.distanceMeters=(member.distanceMeters||0)+distance({lat:before.latitude,lng:before.longitude},{lat:point.latitude,lng:point.longitude});
  if(point.speed!=null){member.speedSampleCount=(member.speedSampleCount||0)+1;member.speedSampleTotal=(member.speedSampleTotal||0)+point.speed;member.maxSpeed=Math.max(member.maxSpeed||0,point.speed*3.6);}
  if(point.timestamp-(member.lastLocationEventAt||0)>=15000){current.timeline??={};const id=randomUUID();current.timeline[id]={id,type:'RIDER_LOCATION_UPDATED',text:member.name+' shared a GPS update.',severity:'INFO',at:point.timestamp,userId:member.id};member.lastLocationEventAt=point.timestamp;}
  const events=Object.values(current.timeline||{}).sort((a,b)=>a.at-b.at);for(const e of events.slice(0,Math.max(0,events.length-200)))delete current.timeline[e.id];
  return current;
 });
 // History is private, explicitly opted in at creation and joining, sampled at 10 seconds.
 if(raw.recordReplay){await database().ref(`rideReplays/${event.params.rideId}`).transaction(current=>{if(point.timestamp-(current?.lastAt||0)<10000)return;const frame={at:point.timestamp,progress:0,positions:Object.entries(raw.locations||{}).filter(([,p])=>point.timestamp-p.timestamp>=0&&point.timestamp-p.timestamp<20000).map(([id,p])=>({id,lat:p.latitude,lng:p.longitude}))};const replay=current||{frames:{}};replay.frames??={};replay.frames[String(Math.floor(point.timestamp))]=frame;const keys=Object.keys(replay.frames).sort();for(const k of keys.slice(0,Math.max(0,keys.length-2160)))delete replay.frames[k];replay.lastAt=point.timestamp;return replay;});}
});
export const liveReplayRetention=onSchedule({schedule:'every 24 hours',region:'europe-west1'},async()=>{const rides=await database().ref('rides').orderByChild('recordingExpiresAt').startAt(1).endAt(Date.now()).get();const updates={};rides.forEach(s=>{updates[`rideReplays/${s.key}`]=null;updates[`rides/${s.key}/replay`]=null;});if(Object.keys(updates).length)await database().ref().update(updates);});

export const liveMessageRetention=onSchedule({schedule:'every 24 hours',region:'europe-west1'},async()=>{const inboxes=(await database().ref('liveInboxes').get()).val()||{};const updates={};for(const [uid,rides] of Object.entries(inboxes))for(const [rideId,messages] of Object.entries(rides))for(const [id,message] of Object.entries(messages))if(message.expiresAt&&message.expiresAt<=Date.now())updates[`liveInboxes/${uid}/${rideId}/${id}`]=null;if(Object.keys(updates).length)await database().ref().update(updates);});
