import {useEffect,useState} from 'react';
import {collection,onSnapshot,query,where,Timestamp} from 'firebase/firestore';
import {Send,Radio,MessageCircle} from 'lucide-react';
import {db,configured,call} from '@/lib/firebase';
import {Choice} from './forms';
import type {Ride,Profile} from '@/lib/types';
type DM={id:string;rideId:string;from:string;to:string;text:string;at:number;expiresAt?:number};
export function Communication({ride,profile,onSend,recipient='',onRecipient}:{ride:Ride;profile:Profile;onSend:(text:string,type:string)=>Promise<boolean>;recipient?:string;onRecipient:(id:string)=>void}){const [text,setText]=useState(''),[announcement,setAnnouncement]=useState(false),[dms,setDms]=useState<DM[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const [queryTime,setQueryTime]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setQueryTime(Date.now()),30000);return()=>clearInterval(timer);},[]);const key='letsride-dms-'+ride.id;useEffect(()=>{if(configured&&!ride.simulated){return onSnapshot(query(collection(db!,'directMessages'),where('participants','array-contains',profile.id),where('rideId','==',ride.id),where('expiresAt','>',Timestamp.fromMillis(queryTime+60000))),s=>setDms(s.docs.map(d=>({id:d.id,...d.data()}) as DM).filter(d=>d.rideId===ride.id)),e=>setError(e.message));}const load=()=>{try{setDms(JSON.parse(localStorage.getItem(key)||'[]').filter((d:DM)=>!d.expiresAt||d.expiresAt>Date.now()));}catch{setDms([]);}};load();window.addEventListener('storage',load);return()=>window.removeEventListener('storage',load);},[ride.id,profile.id,queryTime]);
 async function send(value:string){if(!value.trim())return;setBusy(true);setError('');try{if(recipient){if(configured&&!ride.simulated)await call('directMessage',{rideId:ride.id,to:recipient,text:value});else{const next=[...JSON.parse(localStorage.getItem(key)||'[]'),{id:crypto.randomUUID(),rideId:ride.id,from:profile.id,to:recipient,text:value,at:Date.now(),expiresAt:Date.now()+(profile.privacy?.retentionDays||30)*86400000}];localStorage.setItem(key,JSON.stringify(next));setDms(next);}setText('');}else if(await onSend(value,announcement?'announcement':'text'))setText('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const shown=recipient?dms.filter(d=>(d.from===profile.id&&d.to===recipient)||(d.from===recipient&&d.to===profile.id)).sort((a,b)=>a.at-b.at).map(d=>({id:d.id,sender:ride.members.find(m=>m.id===d.from)?.name||'Rider',text:d.text,at:d.at,type:'direct'})):ride.messages;
 return <section className="surface communications"><div className="section-heading"><div><span className="eyebrow">KEEP THE GROUP CONNECTED</span><h2>Communication center</h2></div><Radio size={21}/></div><Choice label="Message recipient" value={recipient?ride.members.find(m=>m.id===recipient)?.name||'Group':'Group'} onChange={name=>onRecipient(name==='Group'?'':ride.members.find(m=>m.name===name)?.id||'')} options={['Group',...ride.members.filter(m=>m.id!==profile.id).map(m=>m.name)]}/><p className="source-note">{recipient?'Direct conversation · visible only to these two riders':'Group messages · visible to ride members'}{!configured?' · stored in this demo browser':''}</p><div className="quick-messages">{['STOP','HAZARD','FUEL','BREAK','SLOW DOWN','EMERGENCY','REGROUP'].map(q=><button disabled={busy||ride.status==='completed'} key={q} onClick={()=>setText(q==='EMERGENCY'?'I need assistance. Please check in with me.':q==='REGROUP'?'Please regroup at the next safe stopping point.':q==='SLOW DOWN'?'Keep a comfortable, safe pace. No need to catch up.':q)}>{q}</button>)}</div><div className="messages" aria-live="polite">{shown.length===0&&<div className="empty"><MessageCircle/><p>No messages in this conversation yet.</p></div>}{shown.map(m=><div key={m.id} className={'message '+m.type}><div><b>{m.sender}</b><small>{new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div><p>{m.text}</p></div>)}</div>{ride.status!=='completed'&&<form className="message-form" onSubmit={e=>{e.preventDefault();void send(text);}}>{!recipient&&ride.hostId===profile.id&&<Choice label="Group message type" value={announcement?'Leader announcement':'Group message'} onChange={v=>setAnnouncement(v==='Leader announcement')} options={['Group message','Leader announcement']}/>}<div><input value={text} onChange={e=>setText(e.target.value)} required maxLength={2000} aria-label="Message" placeholder={recipient?'Private message…':'Message the group…'}/><button disabled={busy} className="button primary" aria-label="Send message"><Send size={18}/></button></div></form>}{error&&<p className="error">{error}</p>}</section>;
}
