import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {resolvePlace,requestRoute,type Place} from '@/services/navigation';
import type {Ride,Member} from '@/lib/types';
export function DemoRoadMap({ride,onRider,onRoute}:{ride:Ride;onRider:(m:Member)=>void;onRoute:(path:{lat:number;lng:number}[])=>void}){
 const canvas=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),markers=useRef(new Map<string,{marker:L.Marker;frame?:number}>()),line=useRef<L.Polyline|null>(null),overlays=useRef<L.LayerGroup|null>(null);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[distance,setDistance]=useState('');const path=(ride as Ride&{simulationPath?:{lat:number;lng:number}[]}).simulationPath;
 useEffect(()=>{if(!canvas.current)return;const instance=L.map(canvas.current,{scrollWheelZoom:false}).setView([48.7,8.7],9);map.current=instance;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(instance);overlays.current=L.layerGroup().addTo(instance);const observer=new ResizeObserver(()=>instance.invalidateSize());observer.observe(canvas.current);return()=>{observer.disconnect();for(const item of markers.current.values())if(item.frame)cancelAnimationFrame(item.frame);markers.current.clear();instance.remove();map.current=null;};},[ride.id]);
 useEffect(()=>{if(!map.current)return;for(const member of ride.members){if(!member.location)continue;let item=markers.current.get(member.id);const element=document.createElement('div');element.className='google-rider-marker '+(member.id===ride.hostId?'leader':member.id===ride.sweepId?'sweep':member.status==='Offline'?'offline':'rider');const initials=document.createElement('span');initials.className='marker-avatar';initials.textContent=member.id===ride.hostId?'★':member.name.slice(0,2);const label=document.createElement('span');label.className='marker-name';label.textContent='DEMO · '+member.name;const status=document.createElement('small');status.textContent=member.status;element.append(initials,label,status);const icon=L.divIcon({html:element,className:'demo-rider-shell',iconSize:[135,42],iconAnchor:[66,42]});if(!item){const marker=L.marker([member.location.lat,member.location.lng],{icon}).addTo(map.current).on('click',()=>onRider(member));item={marker};markers.current.set(member.id,item);}else item.marker.setIcon(icon);if(item.frame)cancelAnimationFrame(item.frame);const from=item.marker.getLatLng(),to=member.location,start=performance.now(),record=item;const animate=(time:number)=>{const t=Math.min(1,(time-start)/1500);record.marker.setLatLng([from.lat+(to.lat-from.lat)*t,from.lng+(to.lng-from.lng)*t]);if(t<1)record.frame=requestAnimationFrame(animate);};item.frame=requestAnimationFrame(animate);}},[ride.members]);
 useEffect(()=>{if(!map.current||!path?.length)return;line.current?.remove();line.current=L.polyline(path.map(p=>[p.lat,p.lng]),{color:'#c3e58e',weight:5}).addTo(map.current);map.current.fitBounds(line.current.getBounds(),{padding:[30,30]});},[JSON.stringify(path)]);
 useEffect(()=>{const layer=overlays.current;layer?.clearLayers();if(!layer)return;for(const h of ride.hazards||[]){const span=document.createElement('span');span.className='google-map-label hazard';span.textContent='DEMO ⚠ '+h.type;L.marker([h.location.lat,h.location.lng],{icon:L.divIcon({html:span,className:'demo-label-shell'})}).addTo(layer);}for(const e of ride.events.filter(e=>e.location&&!['Resolved','Cancelled'].includes(e.status))){const span=document.createElement('span');span.className='google-map-label sos';span.textContent='DEMO SOS · '+e.name;L.marker([e.location!.lat,e.location!.lng],{icon:L.divIcon({html:span,className:'demo-label-shell'})}).addTo(layer);}},[ride.hazards,ride.events]);
 async function loadRoute(){setBusy(true);setError('');try{const places:Place[]=[];for(const name of [ride.start,...ride.stops,ride.destination])places.push(await resolvePlace(name));const result=await requestRoute(places);onRoute(result.geometry);setDistance((result.distance/1000).toFixed(1)+' km · real OSRM road geometry');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="google-group-map"><div className="group-map-heading"><span className="eyebrow">DEMO RIDE · SIMULATED GPS ON OPENSTREETMAP</span><strong>8 synthetic riders · no location permission requested</strong><span>{distance|| (path?'Real road geometry loaded':'Load the road route to simulate movement along actual roads.')}</span></div><div ref={canvas} className="google-map-canvas"/><div className="group-map-controls"><button className="button primary" disabled={busy} onClick={()=>void loadRoute()}>{busy?'Loading road route…':'Load real road route for demo'}</button><button className="button" onClick={()=>{if(map.current){const points=ride.members.filter(m=>m.location).map(m=>[m.location!.lat,m.location!.lng] as L.LatLngTuple);if(points.length)map.current.fitBounds(L.latLngBounds(points),{padding:[60,60]});}}}>Fit demo riders</button></div>{error&&<p className="error">{error}</p>}<p className="source-note">All rider positions and emergencies on this map are simulated. Demo data is kept in this browser and never sent to a real ride.</p></section>;
}
