import {useState,type ReactNode} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import type {Profile,Ride} from '@/lib/types';
import {configured,login,googleLogin} from '@/lib/firebase';
import {enableNotifications} from '@/lib/notifications';
export function Modal({title,description,open,onClose,children}:{title:string;description?:string;open:boolean;onClose:()=>void;children:ReactNode}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="ride-dialog"><DialogTitle>{title}</DialogTitle><DialogDescription>{description||' '}</DialogDescription>{children}</DialogContent></Dialog>}
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={v=>{if(v)onChange(v);}}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
export function CreateForm({create,onDone}:{create:(v:Record<string,any>)=>Promise<{id:string}>;onDone:(id:string)=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[start,setStart]=useState('');return <form className="form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await create({name:f.get('name'),start:f.get('start'),destination:f.get('destination'),date:f.get('date'),departure:f.get('departure'),description:f.get('description')||'',maxRiders:Number(f.get('maxRiders')),stops:String(f.get('stops')||'').split('\n').map(s=>s.trim()).filter(Boolean)});onDone(r.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <Field label="Ride name"><input name="name" required maxLength={100} placeholder="e.g. Black Forest Adventure Ride"/></Field><Field label="Starting location"><input name="start" required maxLength={180} placeholder="City, address, or coordinates" value={start} onChange={e=>setStart(e.target.value)}/></Field><button type="button" className="text-button" onClick={()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>setStart(`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`),()=>setError('Location unavailable. Enter your meeting point manually.')):setError('Location is not supported in this browser.')}>Use my current location</button><Field label="Destination"><input name="destination" required maxLength={180} placeholder="Where are we heading?"/></Field><div className="two-col"><Field label="Ride date"><input type="date" name="date" required defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="Departure time"><input name="departure" type="time" required defaultValue="09:00"/></Field></div><Field label="Maximum riders"><input type="number" name="maxRiders" min={1} max={50} defaultValue={12} required/></Field><Field label="Meeting instructions"><textarea name="description" maxLength={1000} placeholder="Meeting point, departure plan, and anything the group should know"/></Field><Field label="Stops (one address per line)"><textarea name="stops" placeholder="Fuel station, café, scenic viewpoint…"/></Field>{error&&<p role="alert" className="error">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Creating…':'Create ride & get join code'}</button></form>}
export function JoinForm({lookup,join,onDone}:{lookup:(code:string)=>Promise<any>;join:(code:string)=>Promise<{id:string}>;onDone:(id:string)=>void}){const [code,setCode]=useState(''),[preview,setPreview]=useState<Ride|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <form className="form-grid" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{if(preview){const r=await join(code);onDone(r.id);}else setPreview(await lookup(code));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Field label="6-character join code"><input className="code-input" value={code} onChange={e=>{setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6));setPreview(null);}} minLength={6} maxLength={6} required placeholder="RIDE7X" autoComplete="off"/></Field>{!configured&&<p className="muted">Try RIDE7X in this demo. Demo rides sync only between tabs in this browser.</p>}{preview&&<div className="join-preview"><span className="eyebrow">YOU’RE INVITED</span><h2>{preview.name}</h2><p>Hosted by {preview.hostName}</p><p>{preview.start} → {preview.destination}</p><p>{preview.date} · {preview.departure}</p></div>}{error&&<p className="error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Please wait…':preview?'Join this ride':'Find ride'}</button></form>}
export function ProfileForm({profile,save}:{profile:Profile;save:(p:Profile)=>Promise<void>}){const [consent,setConsent]=useState(profile.sharePhone),[note,setNote]=useState(''),[busy,setBusy]=useState(false);return <form className="form-grid profile-form panel" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await save({...profile,...Object.fromEntries(f),sharePhone:consent} as Profile);setNote('Profile saved.');}catch(e){setNote((e as Error).message);}finally{setBusy(false);}}}><h2>Your rider profile</h2><div className="two-col">{[['name','Name'],['vehicle','Your motorcycle / bicycle'],['phone','Phone number'],['registration','Registration (optional)'],['contactName','Emergency contact name'],['contactPhone','Emergency contact phone'],['relationship','Relationship']].map(([name,label])=><Field key={name} label={label}><input name={name} defaultValue={String(profile[name as keyof Profile]||'')} required={name==='name'} maxLength={120} type={name.toLowerCase().includes('phone')?'tel':'text'}/></Field>)}</div><label className="check-row"><Checkbox checked={consent} onCheckedChange={v=>setConsent(!!v)}/>Allow the host to access my phone and emergency contact while my SOS is open.</label><p className="muted">Emergency contacts are private. Your live location is shared only when you explicitly enable it during an active ride.</p><button className="button primary" disabled={busy}>{busy?'Saving…':'Save profile'}</button><button type="button" className="button" onClick={()=>enableNotifications().then(()=>setNote('Push notifications enabled on this device.')).catch(e=>setNote(e.message))}>Enable ride notifications</button><p role="status">{note}</p></form>}
export function LoginForm(){const [register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <section className="auth-card panel"><span className="eyebrow">YOUR GROUP. ONE DESTINATION.</span><h1>{register?'Join the adventure.':'Welcome back.'}</h1><p className="muted">Sign in to your private riding space.</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await login(String(f.get('email')),String(f.get('password')),register);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Field label="Email"><input name="email" type="email" autoComplete="email" required/></Field><Field label="Password"><input name="password" type="password" minLength={8} autoComplete={register?'new-password':'current-password'} required/></Field><button className="button primary" disabled={busy}>{register?'Create account':'Sign in'}</button></form><button className="button" onClick={()=>googleLogin().catch(e=>setError(e.message))}>Continue with Google</button><button className="text-button" onClick={()=>setRegister(!register)}>{register?'Already have an account? Sign in':'New here? Create an account'}</button>{error&&<p className="error" role="alert">{error}</p>}</section>}

