import {useEffect,useRef,useState,useMemo} from 'react';
import {Navigation,Users,Maximize,Route as RouteIcon,Flag,TriangleAlert} from 'lucide-react';
import {loadGoogleMaps,mapsConfigured,googleRoute,type SharedRoute} from '@/services/google-maps';
import {awareness,distance} from '@/services/location';
import {locationState} from '../functions/realtime-model.mjs';
import {navigationUrl} from '@/services/navigation';
import {sharedRouteProgress,bearingBetween} from '@/services/group-route';
import {configured,auth} from '@/lib/firebase';
import {realtimeAction} from '@/services/realtime';
import type {Ride,Member} from '@/lib/types';
type Follow='none'|'group'|'me'|string;
type MarkerRecord={marker:google.maps.marker.AdvancedMarkerElement;element:HTMLButtonElement;point:google.maps.LatLngLiteral;frame?:number;signature:string};
export function GoogleGroupMap({ride,onRider,onHazard,replayFrame}:{ride:Ride;onRider?:(member:Member)=>void;onHazard?:()=>void;replayFrame?:{at:number;positions:{id:string;lat:number;lng:number}[]}}){
 const canvas=useRef<HTMLDivElement>(null),map=useRef<google.maps.Map|null>(null),markers=useRef(new Map<string,MarkerRecord>()),routeLine=useRef<google.maps.Polyline|null>(null),special=useRef<google.maps.marker.AdvancedMarkerElement[]>([]),fitTime=useRef(0),lastRouteRevision=useRef(0);
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[follow,setFollow]=useState<Follow>('group'),[picked,setPicked]=useState(''),[busy,setBusy]=useState(false),[routeUpdated,setRouteUpdated]=useState(false),[preview,setPreview]=useState<SharedRoute|null>(null),[now,setNow]=useState(Date.now());
 const uid=auth?.currentUser?.uid||ride.hostId,leader=uid===ride.hostId;const shared=(ride as Ride&{sharedRoute?:SharedRoute}).sharedRoute,route=shared||preview;const rows=awareness(ride,now),selected=rows.find(m=>m.id===picked),own=rows.find(m=>m.id===uid);const emergency=ride.events.find(e=>!['Resolved','Cancelled'].includes(e.status));const ownProgress=useMemo(()=>own?.fresh?sharedRouteProgress(route,own.location):null,[route?.updatedAt,own?.location?.lat,own?.location?.lng,own?.fresh]);const latest=useRef({ride,rows,follow,onRider});latest.current={ride,rows,follow,onRider};
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{
  if(!mapsConfigured||!canvas.current)return;let alive=true;
  loadGoogleMaps().then(async()=>{const [{Map:GoogleMap}]=await Promise.all([google.maps.importLibrary('maps'),google.maps.importLibrary('marker')]);if(!alive||!canvas.current)return;map.current=new (GoogleMap as typeof google.maps.Map)(canvas.current,{center:{lat:50.8,lng:10.4},zoom:6,mapId:import.meta.env.VITE_GOOGLE_MAPS_MAP_ID,disableDefaultUI:true,zoomControl:true,gestureHandling:'cooperative'});map.current.addListener('dragstart',()=>setFollow('none'));setReady(true);}).catch(e=>{if(alive)setError(e.message);});
  return()=>{alive=false;for(const item of markers.current.values()){if(item.frame)cancelAnimationFrame(item.frame);item.marker.map=null;}markers.current.clear();special.current.forEach(m=>m.map=null);special.current=[];routeLine.current?.setMap(null);if(map.current)google.maps.event.clearInstanceListeners(map.current);map.current=null;};
 },[ride.id]);
 useEffect(()=>{if(!shared)return;if(lastRouteRevision.current&&shared.revision!==lastRouteRevision.current)setRouteUpdated(true);lastRouteRevision.current=shared.revision;},[shared?.revision]);
 function fitRiders(){if(!map.current)return;const points=latest.current.rows.filter(m=>m.location&&locationState(m)!=='GPS_ANOMALY').map(m=>m.location!);if(!points.length)return;const bounds=new google.maps.LatLngBounds();points.forEach(p=>bounds.extend(p));map.current.fitBounds(bounds,70);if(points.length===1)map.current.setZoom(15);}
 useEffect(()=>{
  if(!ready||!map.current)return;const present=new Set<string>();
  for(const member of rows){const replayPosition=replayFrame?.positions.find(p=>p.id===member.id);const position=replayPosition||member.location;if(!position)continue;const state=replayFrame?'REPLAY':locationState(member,now);if(state==='GPS_ANOMALY')continue;present.add(member.id);const role=member.id===ride.hostId?'leader':member.id===ride.sweepId?'sweep':'rider';const status=state!=='LIVE'&&state!=='WEAK GPS'?state:member.state;const signature=[position.lat,position.lng,member.location?.heading,status,member.name,role,member.speed].join('|');let item=markers.current.get(member.id);
   if(!item){const element=document.createElement('button');element.type='button';element.addEventListener('click',()=>setPicked(member.id));const marker=new google.maps.marker.AdvancedMarkerElement({map:map.current,position:{lat:position.lat,lng:position.lng},content:element,title:member.name,zIndex:role==='leader'?20:10});item={marker,element,point:{lat:position.lat,lng:position.lng},signature:''};markers.current.set(member.id,item);}
   if(item.signature===signature)continue;item.signature=signature;item.element.className=`google-rider-marker ${role} ${status.toLowerCase().replaceAll(' ','-')}`;item.element.replaceChildren();const arrow=document.createElement('span');arrow.className='rider-heading-arrow';arrow.textContent='▲';if(member.location?.heading==null)arrow.style.display='none';arrow.style.transform=`rotate(${member.location?.heading||0}deg)`;const avatar=document.createElement('span');avatar.className='marker-avatar';avatar.textContent=role==='leader'?'★':role==='sweep'?'↧':member.name.slice(0,2).toUpperCase();const label=document.createElement('span');label.className='marker-name';label.textContent=`${ride.simulated?'DEMO · ':''}${member.name} · ${role.toUpperCase()}`;const details=document.createElement('small');details.textContent=`${status} · ${state==='LIVE'&&member.speed!=null?member.speed+' km/h':'last '+member.age+'s ago'}`;if(member.photo&&/^https:\/\//.test(member.photo)){const image=document.createElement('img');image.src=member.photo;image.alt=member.name;image.width=24;image.height=24;image.referrerPolicy='no-referrer';avatar.replaceChildren(image);}item.element.append(arrow,avatar,label,details);item.element.setAttribute('aria-label',`${member.name}, ${role}, ${status}`);
   if(item.frame)cancelAnimationFrame(item.frame);const from={...item.point},target={lat:position.lat,lng:position.lng};const begin=performance.now(),record=item;const animate=(t:number)=>{const fraction=Math.min(1,(t-begin)/(document.documentElement.classList.contains('reduce-motion')?1:1500));record.point={lat:from.lat+(target.lat-from.lat)*fraction,lng:from.lng+(target.lng-from.lng)*fraction};record.marker.position=record.point;if(fraction<1)record.frame=requestAnimationFrame(animate);};item.frame=requestAnimationFrame(animate);
  }
  for(const [id,item] of markers.current)if(!present.has(id)){if(item.frame)cancelAnimationFrame(item.frame);item.marker.map=null;markers.current.delete(id);}
  if(follow==='group'&&Date.now()-fitTime.current>2500){fitTime.current=Date.now();fitRiders();}else if(follow!=='none'&&follow!=='group'){const followed=rows.find(m=>m.id===(follow==='me'?uid:follow));if(followed?.location&&locationState(followed,now)==='LIVE')map.current.panTo(followed.location);}
 },[ready,ride.members,now,follow,replayFrame]);
 useEffect(()=>{if(!ready||!map.current)return;routeLine.current?.setMap(null);special.current.forEach(m=>m.map=null);special.current=[];const marker=(point:google.maps.LatLngLiteral,label:string,className:string,click?:()=>void)=>{const button=document.createElement('button');button.className='google-map-label '+className;button.textContent=label;button.type='button';if(click)button.onclick=click;special.current.push(new google.maps.marker.AdvancedMarkerElement({map:map.current!,position:point,content:button,title:label,zIndex:30}));};
  if(route?.path.length){routeLine.current=new google.maps.Polyline({map:map.current,path:route.path,strokeColor:'#acd478',strokeWeight:5});marker(route.path[0],'START','start');marker(route.path[route.path.length-1],'🏁 '+ride.destination,'destination');route.waypoints?.slice(0,-1).forEach((point,i)=>marker(point,String(i+1),'waypoint'));}
  for(const hazard of ride.hazards||[])marker(hazard.location,'⚠ '+hazard.type+' · reported','hazard',onHazard);
  for(const incident of ride.events.filter(e=>!['Resolved','Cancelled'].includes(e.status)&&e.location))marker(incident.location!,'SOS · '+incident.name,'sos',()=>{setPicked(incident.userId);});
  const regroup=(ride as Ride&{regroupPoint?:google.maps.LatLngLiteral}).regroupPoint;if(regroup)marker(regroup,'REGROUP · confirm safe stopping place','regroup');
 },[ready,route?.updatedAt,route?.revision,JSON.stringify(ride.hazards),JSON.stringify(ride.events),JSON.stringify(ride.regroupPoint)]);
 useEffect(()=>{if(ready&&map.current&&emergency?.location){map.current.panTo(emergency.location);map.current.setZoom(15);setFollow('none');setPicked(emergency.userId);}},[ready,emergency?.id]);
 async function generate(){setBusy(true);setError('');try{const result=await googleRoute(ride.start,ride.destination,ride.stops);if(configured&&!ride.simulated)await realtimeAction(ride.id,'sharedRoute',{route:result});else setPreview(result);if(map.current){const bounds=new google.maps.LatLngBounds();result.path.forEach(p=>bounds.extend(p));map.current.fitBounds(bounds,60);setFollow('none');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!mapsConfigured)return <section className="map-setup-state"><RouteIcon size={28}/><h3>MAP API NOT CONFIGURED</h3><p>Real group navigation requires a restricted Google Maps browser key and a map ID. No rider coordinates are invented.</p><a className="button" href={import.meta.env.BASE_URL+'?setup=1'}>Open developer setup</a>{ride.simulated&&<p>Use the clearly labelled demo map to explore simulated group behavior.</p>}</section>;
 return <section className={'google-group-map '+(emergency?'emergency-mode':'')} aria-label={ride.simulated?'DEMO Google Map with simulated riders':'Live Google group map'}>
  <div className="group-map-heading"><span className="eyebrow">{replayFrame?'PRIVATE RIDE REPLAY':ride.simulated?'DEMO · SIMULATED RIDERS':'REAL RIDE · GOOGLE MAPS'}</span><strong>{emergency?'EMERGENCY MODE':rows.some(m=>m.state==='SEPARATED')?'GROUP SEPARATED':rows.some(m=>m.state==='STALE'||m.state==='OFFLINE')?'GROUP WARNING':rows.some(m=>m.fresh)?'GROUP CONNECTED':'WAITING FOR GPS'}</strong><span>{rows.filter(m=>m.fresh).length}/{rows.length} current locations · {rows.filter(m=>m.state==='ACTIVE').length} moving · {rows.filter(m=>m.state==='SEPARATED').length} separated</span></div>
  {routeUpdated&&<div className="warning" role="status">ROUTE UPDATED · Leader changed the route.<button className="button" onClick={()=>{setRouteUpdated(false);if(route&&map.current){const b=new google.maps.LatLngBounds();route.path.forEach(p=>b.extend(p));map.current.fitBounds(b);setFollow('none');}}}>View new route</button></div>}
  {error&&<p className="error" role="alert">{error}</p>}
  <div ref={canvas} className="google-map-canvas"/>
  <div className="group-map-controls"><button className={'button '+(follow==='me'?'primary':'')} onClick={()=>setFollow('me')}><Navigation size={16}/>Follow me</button><button className={'button '+(follow==='group'?'primary':'')} onClick={()=>setFollow('group')}><Users size={16}/>Follow group</button><button className="button" onClick={()=>{setFollow('none');fitRiders();}}><Maximize size={16}/>Fit all riders</button>{follow!=='none'&&<button className="button" onClick={()=>setFollow('none')}>Stop following</button>}</div>
  <div className="shared-route-summary"><span>{route?`${(route.distanceMeters/1000).toFixed(1)} km · ${Math.round(route.durationSeconds/60)} min route estimate`:'No shared Google route published yet.'}</span>{leader&&!replayFrame&&ride.status!=='completed'&&<button className="button" disabled={busy||!ready} onClick={()=>void generate()}><RouteIcon size={16}/>{busy?'Computing route…':ride.simulated?'Preview demo road route':'Publish shared route'}</button>}<a className="button primary" href={navigationUrl(ride.destination,ride.stops)} target="_blank" rel="noreferrer"><Navigation size={16}/>Navigate in Google Maps</a>{ownProgress&&<span>{(ownProgress.remaining/1000).toFixed(1)} km remaining · approximately {ownProgress.estimatedRemainingMinutes} min using the published route estimate · {Math.round(ownProgress.fraction*100)}% progress{ownProgress.gap>100?' · Off the shared route':''}</span>}<small>Turn-by-turn navigation opens Google Maps. This screen tracks your group and displays the shared route.</small></div>
  {selected&&<div className="map-rider-inspector"><div className="section-heading"><h3>{selected.name} · {selected.id===ride.hostId?'Leader':selected.id===ride.sweepId?'Sweep':'Rider'}</h3><button className="icon-button" aria-label="Close rider details" onClick={()=>setPicked('')}>×</button></div><div className="detail-grid">{[['GPS',locationState(selected,now)],['Speed',selected.fresh&&selected.speed!=null?selected.speed+' km/h':'Unavailable'],['Last location',selected.location?selected.age+'s ago':'Unavailable'],['Distance from you',own?.fresh&&selected.fresh?Math.round(distance(own.location!,selected.location!))+' m':'Unavailable'],['From leader',selected.fromLeader!=null?Math.round(selected.fromLeader)+' m':'Unavailable'],['Bearing from you',own?.fresh&&selected.fresh?bearingBetween(own.location!,selected.location!):'Unavailable'],['Battery',selected.battery!=null?selected.battery+'%':'Information unavailable'],['Accuracy',selected.location?.accuracy!=null?Math.round(selected.location.accuracy)+' m':'Unavailable'],['Status',selected.state]].map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><div className="actions"><button className="button primary" onClick={()=>setFollow(selected.id)}>Follow {selected.name}</button><button className="button" onClick={()=>onRider?.(selected)}>Message / safety details</button></div></div>}
  {leader&&route&&ride.status==='active'&&!ride.simulated&&<button className="button regroup-button" disabled={!own?.fresh} onClick={()=>{const nearest=route.path.reduce((best,p,index)=>own?.location&&distance(own.location,p)<distance(own.location,route.path[best])?index:best,0);let target=nearest,remaining=2000;while(target<route.path.length-1&&remaining>0){remaining-=distance(route.path[target],route.path[target+1]);target++;}const point=route.path[target];if(window.confirm('Propose this route point to the group? Check the map and confirm it is an appropriate, safe place to stop.'))void realtimeAction(ride.id,'regroup',{point,label:'Leader-proposed route regroup point'}).catch(e=>setError(e.message));}}><Flag size={16}/>Propose regroup point</button>}
  {!rows.some(m=>m.location)&&<p className="source-note">Waiting for authorized riders to explicitly share their GPS. No static rider positions are shown.</p>}
  <p className="source-note"><TriangleAlert size={14}/>Location updates can stop when the browser is backgrounded or the screen locks. Stop safely before interacting.</p>
 </section>;
}
