import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Copy,Share2,Play,Pause,Flag,Users,MapPin,MessageCircle,ShieldCheck,Siren,Send,Navigation,Check,Plus,Sparkles,CloudSun,Trash2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {Progress} from '@/components/ui/progress';
import {Modal,Field,Choice} from './forms';
import {RideMap} from './ride-map';
import type {Ride,Profile,Location} from '@/lib/types';
import {call,configured} from '@/lib/firebase';
import {fresh as isFresh} from '@/services/location';
import {distance,kinds} from '../functions/domain.mjs';
type Props={ride:Ride;profile:Profile;act:(id:string,action:string,data?:Record<string,any>)=>Promise<void>;initialTab:string;onBack:()=>void;onSos?:()=>void;onCheckIn?:()=>void;onShareGPS?:()=>void;sharingGPS?:boolean};
export function RideDetail({ride:r,profile,act,initialTab,onBack,onSos,onCheckIn,onShareGPS,sharingGPS=false}:Props){
 const [tab,setTab]=useState(initialTab),[modal,setModal]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[announcement,setAnnouncement]=useState(false),[sosType,setSosType]=useState(kinds[0]),[tick,setTick]=useState(Date.now()),[route,setRoute]=useState({distance:'—',duration:'—'}),[answer,setAnswer]=useState(''),[weather,setWeather]=useState<any>(null),[contacts,setContacts]=useState<any>(null);
 const sharing=sharingGPS;const latest=useRef<Location|null>(null),separated=useRef<Record<string,number>>({});
 const host=r.hostId===profile.id,member=r.members.find(m=>m.id===profile.id)!,ready=r.members.filter(m=>m.ready).length,active=r.status==='active',completed=r.status==='completed';
 useEffect(()=>setTab(initialTab),[initialTab]);
 useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),10000);return()=>clearInterval(timer);},[]);
 const run=async(action:string,data:Record<string,any>={})=>{setBusy(true);setError('');try{await act(r.id,action,data);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}};
 latest.current=member.location||null;
 const shareLocation=()=>{setModal('');onShareGPS?.();};
 const fresh=r.members.filter(m=>isFresh(m,tick));const center=fresh.length?{lat:fresh.reduce((a,m)=>a+m.location!.lat,0)/fresh.length,lng:fresh.reduce((a,m)=>a+m.location!.lng,0)/fresh.length}:null;
 const warnings:string[]=[];for(const m of fresh){const d=center?distance(m.location!,center):0;if(d>r.warningDistance){separated.current[m.id]??=tick;if(tick-separated.current[m.id]>=r.delayMinutes*60000)warnings.push(`${m.name} is ${Math.round(d)} m from the group’s center${d>=r.criticalDistance?' — check in at a safe stop':''}.`);}else delete separated.current[m.id];}
 for(const id of Object.keys(separated.current))if(!fresh.some(m=>m.id===id))delete separated.current[id];
 const elapsed=r.startedAt?Math.max(0,Math.floor(((r.endedAt||tick)-r.startedAt)/60000)):0;
 async function ai(question:string){setError('');const preparation='Before departure, check tires, fuel or charge, protective gear, documents, water and your emergency contact. Confirm the meeting point and group signals with the leader.';const breaks='Discuss fuel and rest stops with the group before departure. Stop at safe locations when anyone needs a break. The app cannot assess fatigue or certify a safe stopping place.';setAnswer(question.toLowerCase().includes('break')?breaks:preparation+` This ride has ${r.members.length} members and ${r.stops.length} planned stops. Check current weather separately.`);}
 async function getWeather(){setBusy(true);setError('');try{if(!configured)throw new Error('Connect the weather service to retrieve current conditions.');setWeather(await call('liveRideWeather',{rideId:r.id}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button className="text-button back" onClick={onBack}><ArrowLeft size={16}/>My rides</button><div className="page-title"><div><span className="pill">{r.status==='active'?'RIDE IN PROGRESS':r.status.toUpperCase()}</span><h1>{r.name}<span>.</span></h1><p className="muted">Hosted by {r.hostName} · {r.date} at {r.departure}</p></div><div className="actions"><button className="button" onClick={()=>{setModal('share');setNote('');}}><Share2 size={16}/>Invite riders</button>{!host&&!completed&&<button className="button" onClick={()=>setConfirm('leave')}>Leave ride</button>}</div></div>
 {error&&<div role="alert" className="error">{error}<button className="text-button" onClick={()=>setError('')}>Dismiss</button></div>}{note&&<p className="success" role="status">{note}</p>}
 {(active||r.status==='paused')&&<div className="riding-warning"><ShieldCheck size={18}/>Keep your attention on the road. Stop safely before interacting with the app.</div>}
 {warnings.map(w=><div className="warning" key={w}>{w} Separation alone does not indicate an emergency.</div>)}
 {r.events.filter(e=>!['Resolved','Cancelled'].includes(e.status)).map(e=><section className="sos-event" key={e.id}><div><span className="eyebrow">{configured?'EMERGENCY ALERT':'DEMO EMERGENCY ALERT'}</span><h2><Siren size={24}/>{e.name} needs assistance</h2><p>{e.type} · {new Date(e.at).toLocaleTimeString()} · {e.status}</p><p>{e.location?`${e.location.lat.toFixed(6)}, ${e.location.lng.toFixed(6)} · Location at time of SOS`:'No location available. Contact the rider to confirm their position.'}</p></div><div className="actions">{e.location&&<a className="button" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${e.location.lat},${e.location.lng}`}>Navigate to rider</a>}{host&&<><button className="button" onClick={async()=>{setError('');try{if(!configured)throw new Error('Demo riders have no real contact details.');setContacts(await call('liveEmergencyContact',{rideId:r.id,eventId:e.id}));setModal('contacts');}catch(err){setError((err as Error).message);}}}>Contact rider</button>{['Acknowledged','Help on the way','Resolved'].filter(s=>['Reported','Acknowledged','Help on the way','Resolved'].indexOf(s)>['Reported','Acknowledged','Help on the way','Resolved'].indexOf(e.status)).map(status=><button className={'button '+(status==='Resolved'?'':'danger')} key={status} disabled={busy} onClick={()=>run('respond',{eventId:e.id,status})}>{status}</button>)}</>}</div></section>)}
 <div className="ride-detail-grid"><div><div className="ride-summary-bar"><span><MapPin size={17}/><b>{r.start}</b><ArrowLeft className="reverse" size={15}/>{r.destination}</span><span>{route.distance} · {route.duration}</span></div><RideMap ride={r} onRoute={setRoute}/><div className="ride-metrics"><div><span>Group readiness</span><b>{ready} / {r.members.length}</b></div><div><span>Fresh locations</span><b>{fresh.length} / {r.members.length}</b></div><div><span>{completed?'Total duration':'Elapsed time'}</span><b>{r.startedAt?`${Math.floor(elapsed/60)}h ${elapsed%60}m`:'Not started'}</b></div></div>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="ride-tabs"><TabsTrigger value="group"><Users size={16}/>Group</TabsTrigger><TabsTrigger value="chat"><MessageCircle size={16}/>Chat</TabsTrigger><TabsTrigger value="route"><Flag size={16}/>Route</TabsTrigger><TabsTrigger value="assistant"><Sparkles size={16}/>Assistant</TabsTrigger></TabsList></Tabs>
 {tab==='group'&&<section className="panel group-panel"><div className="section-heading"><h2>Your riding crew</h2><span>{ready} of {r.members.length} ready</span></div><Progress value={100*ready/Math.max(1,r.members.length)} className="ready-progress"/>{r.members.map(m=><div className="member-row" key={m.id}><span className="avatar">{m.name.slice(0,2).toUpperCase()}</span><div><b>{m.name}{m.id===profile.id?' (you)':''}</b><p>{m.vehicle}{m.id===r.hostId?' · Host':''}</p></div><span className={'member-status '+(m.status==='Emergency'?'red':'')}>{m.status}{active&&m.location&&tick-m.location.at>120000?' · Location stale':''}</span>{host&&m.id!==profile.id&&!completed&&<button aria-label={`Remove ${m.name}`} className="icon-button" onClick={()=>setConfirm(`remove:${m.id}`)}><Trash2 size={15}/></button>}</div>)}</section>}
 {tab==='chat'&&<section className="panel"><div className="section-heading"><h2>Group conversation</h2><span>{configured?'Realtime':'Demo · this browser'}</span></div><div className="messages" aria-live="polite">{r.messages.length===0&&<p className="muted">Start the conversation. Say hello to your group.</p>}{r.messages.map(m=><div className={'message '+m.type} key={m.id}><div><b>{m.sender}</b><small>{new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}{m.type==='announcement'?' · Announcement':''}</small></div><p>{m.text}</p></div>)}</div>{!completed&&<form className="message-form" onSubmit={async e=>{e.preventDefault();if(!message.trim())return;if(await run('message',{text:message,type:announcement?'announcement':'text'}))setMessage('');}}>{host&&<Choice label="Message type" options={['Group message','Host announcement']} value={announcement?'Host announcement':'Group message'} onChange={v=>setAnnouncement(v==='Host announcement')}/>}<div><input aria-label="Message to group" value={message} maxLength={2000} onChange={e=>setMessage(e.target.value)} placeholder="Message your group…" required/><button className="button primary" disabled={busy} aria-label="Send message"><Send size={18}/></button></div><button type="button" className="text-button" onClick={()=>{if(!latest.current){setError('Enable location sharing first to share a current position.');return;}setMessage(`My location: https://www.google.com/maps/search/?api=1&query=${latest.current.lat},${latest.current.lng}`);}}>Attach my location</button></form>}</section>}
 {tab==='route'&&<section className="panel"><h2>The way there</h2><div className="stop"><MapPin/><div><b>Meeting point</b><p>{r.start}</p><p>{r.description}</p></div></div>{r.stops.map((s,i)=><div className="stop" key={i}><span className="stop-number">{i+1}</span><p>{s}</p></div>)}<div className="stop"><Flag/><div><b>Destination</b><p>{r.destination}</p></div></div>{host&&!completed&&<form className="inline-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await run('stop',{stop:new FormData(form).get('stop')}))form.reset();}}><input name="stop" aria-label="Stop address" required maxLength={120} placeholder="Add a fuel, rest, or scenic stop"/><button className="button" disabled={busy}><Plus size={16}/>Add stop</button></form>}<button className="button weather-button" disabled={busy} onClick={getWeather}><CloudSun size={18}/>Check current weather</button>{weather&&<div className="notice"><p>Destination · {weather.temperature}°C · Wind {weather.wind} km/h</p><p>Rain probability: {weather.rainProbability??'Unavailable'}%</p><small>Open-Meteo · {weather.time}</small></div>}</section>}
 {tab==='assistant'&&<section className="panel assistant-panel"><Sparkles size={25}/><h2>A little help for the road ahead.</h2><p className="muted">Ride context and general preparation guidance. This helper does not use a live AI model.</p><div className="actions">{['Create a checklist for this ride','Suggest a sensible break schedule','What should I carry?'].map(q=><button className="button" key={q} disabled={busy} onClick={()=>ai(q)}>{q}</button>)}</div><form className="inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void ai(String(f.get('question')));}}><input name="question" required maxLength={1000} aria-label="Ask the ride assistant" placeholder="Ask about this ride…"/><button className="button primary" disabled={busy}>Ask</button></form>{busy&&<p role="status">Working on it…</p>}{answer&&<div className="assistant-answer">{answer}</div>}<p className="muted">Suggestions are advisory. Follow official navigation, weather, and emergency guidance.</p></section>}
 </div><aside className="ride-controls"><section className="panel"><span className="eyebrow">{completed?'RIDE COMPLETE':'YOUR RIDE STATUS'}</span><h2>{completed?'That’s a wrap.':active?'Together on the road.':'Ready when you are.'}</h2>{!completed&&<><button className={'button full '+(member.ready?'':'primary')} disabled={busy} onClick={()=>!member.ready&&onCheckIn?onCheckIn():run('ready',{ready:!member.ready})}><Check size={18}/>{member.ready?'Ready · tap to undo':'I’m ready'}</button>{active&&<><Field label="Rider status"><Choice label="Your rider status" value={['Riding','Stopped','Delayed','Offline'].includes(member.status)?member.status:'Stopped'} options={['Riding','Stopped','Delayed','Offline']} onChange={status=>run('status',{status})}/></Field><button className="button full" onClick={async()=>{onShareGPS?.();}}><Navigation size={16}/>{sharing?'Stop location sharing':'Share live location'}</button><p className="muted small">{sharing?'Sharing while this screen is open. Updates approximately every 3 seconds.':'Your location is not being shared.'}</p></>}{host&&<div className="host-actions"><span className="eyebrow">HOST CONTROLS</span>{r.status==='upcoming'||r.status==='paused'?<button className="button primary full" disabled={busy} onClick={()=>setConfirm('start')}><Play size={18}/>{r.status==='paused'?'Resume ride':'Start ride'}</button>:<button className="button full" disabled={busy} onClick={()=>run('pause')}><Pause size={18}/>Pause ride</button>}{['active','paused'].includes(r.status)&&<button className="button full" onClick={()=>setConfirm('end')}><Flag size={18}/>End ride</button>}<button className="text-button" onClick={()=>setModal('settings')}>Group separation settings</button></div>}</>}{completed&&<><p className="muted">{r.members.length} riders · {r.stops.length} stops · {r.events.length} emergency events</p><p>{r.start} → {r.destination}</p><p className="muted">Live positions were removed when the ride ended.</p></>}{host&&<button className="text-button delete-link" onClick={()=>setConfirm('delete')}>Delete ride</button>}</section>{!completed&&<section className="sos-panel"><Siren size={27}/><h2>Need assistance?</h2><p>Alert your group with your location and emergency type.</p><button className="button danger full" disabled={!['active','paused'].includes(r.status)} onClick={()=>onSos?onSos():setModal('sos')}>SOS · Emergency</button><small>{active?'Confirmation required. No automatic emergency calls.':'Available when the ride is in progress.'}</small></section>}<section className="panel code-panel"><span className="eyebrow">YOUR GROUP’S JOIN CODE</span><strong>{r.code}</strong><button className="text-button" onClick={()=>navigator.clipboard.writeText(r.code).then(()=>setNote('Join code copied.')).catch(()=>setNote(`Join code: ${r.code}`))}><Copy size={15}/>Copy code</button></section></aside></div>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v&&!busy)setConfirm('');}}><AlertDialogContent className="ride-dialog"><AlertDialogTitle>{confirm==='start'?'Ready to start this ride?':confirm==='end'?'End this ride?':confirm==='delete'?'Permanently delete this ride?':confirm==='leave'?'Leave this ride?':'Remove this rider?'}</AlertDialogTitle><AlertDialogDescription>{confirm==='start'?`${r.members.length} riders · ${r.destination}. ${ready} of ${r.members.length} ready. ${ready<r.members.length?'Some riders are not ready. Check with the group before departure.':''}`:confirm==='end'?'This completes the ride for everyone and removes shared location data.':confirm==='delete'?'The ride, messages, and emergency records will be deleted for everyone.':'The rider will lose access to the ride and shared locations.'}</AlertDialogDescription><div className="actions"><button className="button" onClick={()=>setConfirm('')}>Cancel</button><button className={'button '+(confirm==='start'?'primary':'danger')} disabled={busy} onClick={async()=>{const action=confirm.split(':')[0];if(await run(action,action==='start'?{confirmUnready:true}:action==='remove'?{userId:confirm.split(':')[1]}:{})){setConfirm('');if(['delete','leave'].includes(action))onBack();}}}>{busy?'Please wait…':confirm==='start'?'Start ride':'Confirm'}</button></div>{error&&<p className="error">{error}</p>}</AlertDialogContent></AlertDialog>
 <Modal open={modal==='share'} onClose={()=>setModal('')} title="Bring your people" description="Share this code with the riders you want to invite."><div className="share-code">{r.code}</div><div className="actions"><button className="button primary" onClick={()=>navigator.clipboard.writeText(r.code).then(()=>setNote('Code copied.')).catch(()=>setNote('Select and copy the code above.'))}><Copy size={16}/>Copy code</button>{typeof navigator.share==='function'&&<button className="button" onClick={()=>navigator.share({title:r.name,text:`Join ${r.name} on Let’s Ride. Code: ${r.code}`}).catch(()=>{})}>Share</button>}<a className="button" href={`https://wa.me/?text=${encodeURIComponent(`Join ${r.name} on Let’s Ride. Code: ${r.code}`)}`} target="_blank" rel="noreferrer">WhatsApp</a><a className="button" href={`sms:?body=${encodeURIComponent(`Join ${r.name}. Code: ${r.code}`)}`}>SMS</a></div>{note&&<p role="status">{note}</p>}</Modal>
 <Modal open={modal==='location'} onClose={()=>setModal('')} title="Share your live location?" description="Your live location will be shared with members of this active ride to help coordinate the group and respond to emergencies."><p>Sharing stops when you leave this screen or the ride is paused or completed. Mobile browsers may suspend tracking when locked.</p><button className="button primary" onClick={shareLocation}>Allow location sharing</button></Modal>
 <Modal open={modal==='sos'} onClose={()=>setModal('')} title={configured?'Send an emergency alert?':'Send a demo emergency alert?'} description="Your host and group will see this alert. Emergency services will not be contacted automatically."><Field label="Type of emergency"><Choice label="Emergency type" value={sosType} onChange={setSosType} options={kinds}/></Field><p>{latest.current?'Your most recent location will be attached.':'No current location available. Your alert will state that your location is unknown.'}</p><div className="actions"><button className="button" onClick={()=>setModal('')}>Cancel</button><button className="button danger" disabled={busy} onClick={async()=>{const location=latest.current&&Date.now()-latest.current.at<60000?latest.current:null;if(await run('sos',{type:sosType,location}))setModal('');}}>Send SOS</button></div>{error&&<p className="error">{error}</p>}</Modal>
 <Modal open={modal==='settings'} onClose={()=>setModal('')} title="Group separation settings" description="Warnings help coordinate the group. Separation is never automatically classified as an emergency."><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run('settings',{warningDistance:Number(f.get('warning')),criticalDistance:Number(f.get('critical')),delayMinutes:Number(f.get('delay'))}))setModal('');}}><Field label="Warning distance (meters)"><input type="number" name="warning" required min={100} max={10000} defaultValue={r.warningDistance}/></Field><Field label="Critical distance (meters)"><input type="number" name="critical" required min={100} max={20000} defaultValue={r.criticalDistance}/></Field><Field label="Warning delay (minutes)"><input type="number" name="delay" required min={1} max={30} defaultValue={r.delayMinutes}/></Field><button className="button primary" disabled={busy}>Save settings</button>{error&&<p className="error">{error}</p>}</form></Modal>
 <Modal open={modal==='contacts'} onClose={()=>{setModal('');setContacts(null);}} title="Emergency contacts" description="Shared with the host by the rider’s consent for this open emergency.">{contacts?.phone&&<a className="button" href={`tel:${contacts.phone}`}>Call rider</a>}{contacts?.contactPhone&&<a className="button" href={`tel:${contacts.contactPhone}`}>Call {contacts.contactName||'emergency contact'}</a>}{!contacts?.phone&&!contacts?.contactPhone&&<p>No contact details shared by this rider.</p>}</Modal>
 </>;
}
