import {useEffect,useRef,useState} from 'react';
import {MapPin,Navigation} from 'lucide-react';
import type {Ride} from '@/lib/types';
declare global {interface Window {google:any;initRideMap?:()=>void}}
let mapsPromise:Promise<void>|null=null;
function loadMaps(){if(window.google?.maps)return Promise.resolve();if(!mapsPromise)mapsPromise=new Promise((resolve,reject)=>{window.initRideMap=resolve;const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(import.meta.env.VITE_GOOGLE_MAPS_API_KEY)}&callback=initRideMap&libraries=places`;s.async=true;s.onerror=()=>reject(new Error('Google Maps could not load.'));document.head.appendChild(s);});return mapsPromise;}
export function RideMap({ride,onRoute}:{ride:Ride;onRoute:(v:{distance:string;duration:string})=>void}){const node=useRef<HTMLDivElement>(null),map=useRef<any>(null),markers=useRef<any[]>([]),[error,setError]=useState('');
 useEffect(()=>{if(!import.meta.env.VITE_GOOGLE_MAPS_API_KEY)return;let cancelled=false;loadMaps().then(()=>{if(cancelled||!node.current)return;map.current=new window.google.maps.Map(node.current,{center:{lat:48.76,lng:8.24},zoom:9,disableDefaultUI:true,zoomControl:true,styles:[{elementType:'geometry',stylers:[{color:'#242c20'}]},{elementType:'labels.text.fill',stylers:[{color:'#b5c3a2'}]},{elementType:'labels.text.stroke',stylers:[{color:'#242c20'}]}]});new window.google.maps.DirectionsService().route({origin:ride.start,destination:ride.destination,waypoints:ride.stops.map(location=>({location,stopover:true})),travelMode:'DRIVING'},(result:any,status:string)=>{if(cancelled)return;if(status!=='OK'){setError('Route unavailable. Check the start, destination, and stops.');return;}new window.google.maps.DirectionsRenderer({map:map.current,directions:result,polylineOptions:{strokeColor:'#dbfb75',strokeWeight:5}});const legs=result.routes[0].legs;onRoute({distance:`${Math.round(legs.reduce((a:number,l:any)=>a+l.distance.value,0)/1000)} km`,duration:`${Math.round(legs.reduce((a:number,l:any)=>a+l.duration.value,0)/60)} min`});});}).catch(e=>setError(e.message));return()=>{cancelled=true;markers.current.forEach(m=>m.setMap(null));map.current=null;};},[ride.id,ride.start,ride.destination,ride.stops.join('|')]);
 useEffect(()=>{let cancelled=false;if(!import.meta.env.VITE_GOOGLE_MAPS_API_KEY)return;loadMaps().then(()=>{if(cancelled||!map.current)return;markers.current.forEach(m=>m.setMap(null));markers.current=ride.members.filter(m=>m.location&&Date.now()-m.location.at<120000).map(m=>new window.google.maps.Marker({map:map.current,position:m.location,label:m.name.slice(0,1),title:`${m.name} · ${m.status}`,icon:{path:window.google.maps.SymbolPath.CIRCLE,fillColor:m.status==='Emergency'?'#ff6060':m.id===ride.hostId?'#78b6ff':'#dbfb75',fillOpacity:1,strokeColor:'#111',strokeWeight:2,scale:15}}));});return()=>{cancelled=true;};},[ride.members]);
 return <div className="live-map">{import.meta.env.VITE_GOOGLE_MAPS_API_KEY?<div ref={node} className="google-map"/>:<div className="map-empty"><div className="contour"/><div className="map-route"><MapPin/><span>{ride.start}</span><div className="map-dash"/><Navigation/><span>{ride.destination}</span></div><div className="map-note"><b>Route overview</b><p>Connect Google Maps to view the route and live rider markers.</p><small>This diagram is not a navigation map.</small></div></div>}{error&&<p className="error map-error">{error}</p>}<a className="button map-nav" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(ride.start)}&destination=${encodeURIComponent(ride.destination)}&travelmode=driving`}><Navigation size={16}/>Open navigation</a></div>;
}
