import {useEffect,useState} from 'react';
import {onAuthStateChanged} from 'firebase/auth';
import {collection,query,where,onSnapshot,doc,setDoc,getDoc} from 'firebase/firestore';
import {auth,db,configured,call} from './firebase';
import {demoProfile,demoRides} from './seed';
import {changeRide} from '../functions/domain.mjs';
import type {Profile,Ride} from './types';
const KEY='letsride-demo-v1';
export function useRides(){
 const [rides,setRides]=useState<Ride[]>(configured?[]:demoRides),[profile,setProfile]=useState<Profile>(demoProfile),[signedIn,setSignedIn]=useState(!configured),[loading,setLoading]=useState(configured),[error,setError]=useState('');
 useEffect(()=>{if(!configured){try{const saved=localStorage.getItem(KEY);if(saved)setRides(JSON.parse(saved));const p=sessionStorage.getItem('letsride-demo-profile');if(p)setProfile(JSON.parse(p));}catch{setError('Saved demo data could not be loaded.');}const changed=(e:StorageEvent)=>{if(e.key===KEY&&e.newValue){try{setRides(JSON.parse(e.newValue));}catch{}}};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);}let unsub=()=>{};const off=onAuthStateChanged(auth!,async user=>{unsub();setSignedIn(!!user);setLoading(!!user);if(!user){setRides([]);setLoading(false);return;}setProfile({...demoProfile,id:user.uid,name:user.displayName||'Rider',email:user.email||''});try{const p=await getDoc(doc(db!,'users',user.uid));if(p.exists())setProfile(p.data() as Profile);}catch(e){setError(String(e));}unsub=onSnapshot(query(collection(db!,'rides'),where('memberIds','array-contains',user.uid)),snap=>{setRides(snap.docs.map(d=>({...d.data(),id:d.id}) as Ride));setLoading(false);},e=>{setError(e.message);setLoading(false);});});return()=>{off();unsub();};},[]);
 function save(next:Ride[]){localStorage.setItem(KEY,JSON.stringify(next));setRides(next);}
 async function act(id:string,action:string,data:Record<string,any>={}){if(configured){await call('rideAction',{rideId:id,action,...data});return;}const latest=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(rides)) as Ride[];const r=latest.find(r=>r.id===id);if(!r)throw new Error('Ride not found.');if(action==='delete'){if(r.hostId!==profile.id)throw new Error('Only the host can delete rides.');save(latest.filter(r=>r.id!==id));return;}save(latest.map(r=>r.id===id?changeRide(r,profile.id,action,data):r));}
 async function create(data:Record<string,any>){if(configured)return await call<{id:string;code:string}>('createRide',data);const id=crypto.randomUUID(),code=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%31]).join('');const r:Ride={...demoRides[1],...data,id,code,hostId:profile.id,hostName:profile.name,status:'upcoming',memberIds:[profile.id],members:[{id:profile.id,name:profile.name,vehicle:profile.vehicle,ready:false,status:'Not ready',lastUpdated:Date.now()}],messages:[],events:[],stops:data.stops||[],createdAt:Date.now()};save([r,...rides]);return{id,code};}
 async function lookup(code:string){if(configured)return await call<Pick<Ride,'id'|'name'|'hostName'|'start'|'destination'|'date'|'departure'>>('lookupRide',{code});const r=rides.find(r=>r.code===code);if(!r||r.status==='completed')throw new Error('No open ride matches that code.');return r;}
 async function join(code:string){if(configured)return await call<{id:string}>('joinRide',{code});const r=rides.find(r=>r.code===code);if(!r)throw new Error('Ride not found.');if(r.status==='completed')throw new Error('Ride has ended.');if(!r.memberIds.includes(profile.id)){if(r.members.length>=r.maxRiders)throw new Error('This ride is full.');save(rides.map(x=>x.id===r.id?{...x,memberIds:[...x.memberIds,profile.id],members:[...x.members,{id:profile.id,name:profile.name,vehicle:profile.vehicle,ready:false,status:'Not ready',lastUpdated:Date.now()}]}:x));}return{id:r.id};}
 async function saveProfile(p:Profile){if(configured)await setDoc(doc(db!,'users',profile.id),{...p,id:profile.id});else sessionStorage.setItem('letsride-demo-profile',JSON.stringify(p));setProfile(p);}
 return {rides,profile,signedIn,loading,error,setError,act,create,lookup,join,saveProfile};
}
